# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 花楹一间 # 网站标题
subtitle: 'HuaYing Notes blog' # 网站副标题
description: '用于学习记录的博客' # 网站描述
keywords: ["HuaYing", "Hexo", "Blog", "Markdown"] # 网站的关键词
author: Aurora-flower # 作者
language: zh-CN # 网站语言
timezone: 'Asia/Shanghai' # 时区

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://Aurora-flower.github.io # 网站地址
root: / # 网站根目录 - 如：/blog/
permalink: :year/:month/:day/:title/ # 文章的永久链接格式
permalink_defaults: # 永久链接中各部分的默认值
pretty_urls: # 改写 permalink 的值来美化 URL
  trailing_index: false # 是否在永久链接中保留尾部的 'index.html'
  trailing_html: false # 是否在永久链接中保留尾部的 '.html'

# Directory
source_dir: source # 源文件夹，存储内容的位置
public_dir: public # 静态文件夹，静态站点的生成位置
tag_dir: tags # 标签目录
archive_dir: archives # 存档目录
category_dir: categories # 分类目录
code_dir: downloads/code # Include code 文件夹，source_dir 下的子目录
i18n_dir: :lang # 国际化（i18n）文件夹
skip_render: # 匹配到的文件将会被不做改动地复制到 public 目录中。支持 glob 正则表达式。如: "page/**/*"

# Writing
new_post_name: :title.md # 新文章的文件名称
default_layout: post # 预设布局
titlecase: false # 将标题转换为标题卡 - Transform title into titlecase
external_link: # 在新标签中打开链接的配置
  enable: true # 在新标签中打开链接
  field: site # 对整个网站（site）生效或仅对文章（post）生效
  exclude: '' # 需要排除的域名。主域名和子域名如 www 需分别配置
filename_case: 0 # 设置为 1 ，将文件名转换为小写形式； 设置为 2 ，将文件名转换为大写形式。
render_drafts: false # 显示草稿
post_asset_folder: false # 启用资源文件夹
relative_link: true # 把链接改为与根目录的相对位址
future: true # 显示未来的文章
syntax_highlighter: highlight.js # 代码块的设置
highlight: # 代码块的设置
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: true 
prismjs: # 代码块的设置
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator: # 生成帖子归档。由 hexo-generator-index 驱动。- path 表示博客索引页面的根路径	
  path: '' 
  per_page: 10 # 每页显示帖子数
  order_by: -date
  pagination_dir: page # URL 格式

# Category & Tag
default_category: uncategorized # 默认分类
category_map: # 分类别名
  # "C++": c-plus-plus 
tag_map: # 标签别名

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true # 值为 false 时 Hexo 不会在头部插入该标签

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD # 日期格式
time_format: HH:mm:ss # 时间格式
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime' # 当 Front Matter 中没有指定 updated 时 updated 的取值

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10 # 每页显示的帖子数。 0 关闭分页功能
pagination_dir: page # URL 格式 - 如: http://example.com/page/2

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: # 包含隐藏文件（包括名称以下划线开头的文件/文件夹，* 除外）
exclude: # 排除文件或文件夹
ignore: # 忽略文件/文件夹

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape # 当前主题名称。 值为 false 时禁用主题
theme_config: # 主题的配置文件 - 会覆盖主题目录下的 _config.yml 中的配置

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy: # 部署部分的设置
  type: 'git'
  #  repository: https://github.com/Aurora-flower/Aurora-flower.github.io.git
  repository: git@github.com:Aurora-flower/Aurora-flower.github.io.git
  branch: gh-pages
